# Exported from MPLAB IDE project `Tilt Sensor.mcp' on Wed Feb 25 17:37:11 2009.

"Tilt Sensor.cof" : "tilt.o"
	"C:\mcc18\bin\mplink.exe" /l"C:\mcc18\lib" "C:\mcc18\lkr\18f1220.lkr" "C:\Nerd Stuff\uC\Tilt Sensor\tilt.o" /o"Tilt Sensor.cof" /M"Tilt Sensor.map" /W

"tilt.o" : "tilt.c" "C:\Nerd Stuff\uC\Tilt Sensor\tilt.c" "C:\mcc18\h\adc.h" "C:\Nerd Stuff\uC\Tilt Sensor\tilt.c" "C:\mcc18\h\p18f1220.h"
	"C:\mcc18\bin\mcc18.exe" -p=18F1220  /i"C:\mcc18\h" "tilt.c" -fo="tilt.o" -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	del "tilt.o" "Tilt Sensor.cof" "Tilt Sensor.cod" "Tilt Sensor.hex" "Tilt Sensor.lst"

